from __future__ import annotations
from typing import Protocol, runtime_checkable
from src.models import ParticipantCapabilities, ParticipantTurnResult, RoundContext, ValidationResult

@runtime_checkable
class ParticipantPlugin(Protocol):
    id: str
    display_name: str
    capabilities: ParticipantCapabilities

    def validate(self) -> ValidationResult: ...
    def start_session(self, topic: str, system_contract: str) -> str | None: ...
    def send_turn(self, session_id: str | None, round_context: RoundContext) -> ParticipantTurnResult: ...
    def interrupt(self, session_id: str | None) -> bool: ...
    def resume(self, session_id: str) -> bool: ...
    def close_session(self, session_id: str | None) -> None: ...
